{% set name = "sphinx-prompt" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 859f49774865ec06d0e24fa6d80dbe2cbc2922cf82c1a6869ff39ea1f14da9d1

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - python >=3.0
    - pygments
    - sphinx

about:
  home: https://github.com/sbrunner/sphinx-prompt
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx directive to add unselectable prompt
  doc_url: https://github.com/sbrunner/sphinx-prompt/blob/master/README.rst
  dev_url: https://github.com/sbrunner/sphinx-prompt

extra:
  recipe-maintainers:
    - jonathansick
